### ISSUE TITLE
第56页 57页 routes.js内容错误？

### ISSUE THREAD

**Issue by tangj1206** [DotNetAge/vue-bookstore#5]
第56页 main.js里面内容：
const router = newVueRouter（）
移至routes.js里面变成了
export default = new VueRouter（）//此行代码在语法上还报错

**Comment by DotNetAge** [comment]
这里多了一个 "=" ，问题已提交给出版社了。

```js
export default new VueRouter();
```

**Comment by tangj1206** [comment]
感谢您的解答 问题已经解决
